<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <NoWarn>$(NoWarn);CA1707;IL2026;IL3050</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy.Abstractions\EricksonLopez.MultiTenancy.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy\EricksonLopez.MultiTenancy.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy.AspNetCore\EricksonLopez.MultiTenancy.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy.Dapper\EricksonLopez.MultiTenancy.Dapper.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy.PostgreSql\EricksonLopez.MultiTenancy.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy.SqlServer\EricksonLopez.MultiTenancy.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy.MySql\EricksonLopez.MultiTenancy.MySql.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy.MariaDb\EricksonLopez.MultiTenancy.MariaDb.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy.Oracle\EricksonLopez.MultiTenancy.Oracle.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy.Sqlite\EricksonLopez.MultiTenancy.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy.Testing\EricksonLopez.MultiTenancy.Testing.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.MultiTenancy.OpenTelemetry\EricksonLopez.MultiTenancy.OpenTelemetry.csproj" />
  </ItemGroup>

</Project>
